[buildfix] qt/containerUtils: Add missing include
Missing the declaration of std::unique_ptr gave this delightfully unclear error
message:

In file included from ../../dfg/qt/graphTools.hpp:5,
                 from ../../dfg/qt/graphTools.cpp:1:
../../dfg/qt/containerUtils.hpp:98:39: error: declaration of ‘operator=’ as non-function
   98 |     QObjectStorage<T>& operator=(std::unique_ptr<T> other)
      |                                       ^~~~~~~~~~
../../dfg/qt/containerUtils.hpp:98:32: error: expected ‘;’ at end of member declaration
   98 |     QObjectStorage<T>& operator=(std::unique_ptr<T> other)
      |                                ^
      |                                 ;
../../dfg/qt/containerUtils.hpp:98:49: error: expected ‘)’ before ‘<’ token
   98 |     QObjectStorage<T>& operator=(std::unique_ptr<T> other)
      |                                 ~               ^
      |                                                 )